#!/usr/bin/env python3
"""Regenerate Memex's catalog from page frontmatter.

Writes wiki/index.md (root) and one section index per domain:
  one "<Domain> Index.md" per domain folder (see TITLES)
Each line: - [[Page]] — summary · status · updated. Never hand-edit the outputs; fix `summary:` instead.
Usage: python3 meta/tools/build_index.py
"""
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from memexlib import ROOT, DOMAINS, SPECIAL, frontmatter, iter_files, rel  # noqa: E402

SECTION_ORDER = {
    "engineering": ["projects", "systems", "decisions", "playbooks", "incidents", "concepts", "people", "career", "syntheses", "sources"],
    "learning": ["topics", "concepts", "entities", "syntheses", "sources"],
    "personal": ["projects", "areas", "goals", "people", "ideas", "reflections", "syntheses", "sources"],
}
TITLES = {"engineering": "Engineering Index", "learning": "Learning Index", "personal": "Personal Index"}
BLURB = {
    "engineering": "Your own engineering: side projects, open source, repos, tools, decisions, career.",
    "learning": "Transferable knowledge: topics, concepts, tools, papers, articles, courses.",
    "personal": "Life: projects, areas (health, finance, home), goals, people, ideas, reflections.",
}


def load_pages():
    pages = defaultdict(list)
    for p in iter_files(ROOT / "wiki", exts=(".md",)):
        r = rel(p)
        if r in SPECIAL:
            continue
        parts = r.split("/")
        if len(parts) < 3 or parts[1] not in DOMAINS:
            continue
        fm, _ = frontmatter(p.read_text(encoding="utf-8", errors="ignore"))
        folder = parts[2] if len(parts) > 3 else "(root)"
        pages[parts[1]].append({
            "name": p.stem, "folder": folder, "summary": str(fm.get("summary") or "").strip(),
            "status": str(fm.get("status") or "").strip(), "updated": str(fm.get("updated") or "").strip(),
            "reviewed": str(fm.get("reviewed") or "").strip(), "type": str(fm.get("type") or "").strip(),
        })
    return pages


def line(pg):
    bits = [f"- [[{pg['name']}]]"]
    bits.append(f" — {pg['summary']}" if pg["summary"] else " — ⚠ no summary")
    meta = []
    if pg["status"] and pg["status"] not in ("active",):
        meta.append(pg["status"])
    if pg["updated"]:
        meta.append(pg["updated"])
    if not pg["reviewed"]:
        meta.append("unreviewed")
    if meta:
        bits.append(f" · _{' · '.join(meta)}_")
    return "".join(bits)


def write(path: Path, content: str):
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8")
        return True
    return False


def main():
    pages = load_pages()
    changed = []
    for d in DOMAINS:
        items = pages.get(d, [])
        by_folder = defaultdict(list)
        for pg in items:
            by_folder[pg["folder"]].append(pg)
        order = SECTION_ORDER[d] + sorted(f for f in by_folder if f not in SECTION_ORDER[d])
        out = [
            "---", "type: index", f"domain: {d}", "generated: true", "---",
            f"> [!info] Generated by `meta/tools/build_index.py` — do not edit. {len(items)} pages.",
            "", BLURB[d], "",
        ]
        for f in order:
            if f not in by_folder:
                continue
            out.append(f"## {f.capitalize()} ({len(by_folder[f])})")
            out += [line(pg) for pg in sorted(by_folder[f], key=lambda x: x["name"].lower())]
            out.append("")
        if not items:
            out.append("_No pages yet._\n")
        if write(ROOT / "wiki" / d / f"{TITLES[d]}.md", "\n".join(out).rstrip() + "\n"):
            changed.append(TITLES[d])

    everything = [pg for d in DOMAINS for pg in pages.get(d, [])]
    recent = sorted((pg for pg in everything if pg["updated"]), key=lambda x: (x["updated"], x["name"].lower()), reverse=True)[:12]
    unreviewed = sum(1 for pg in everything if not pg["reviewed"])
    root = [
        "---", "type: index", "generated: true", "---",
        "> [!info] Generated by `meta/tools/build_index.py` — do not edit. Start every lookup here, then open a section index.",
        "", "# Memex Index", "",
        f"**{len(everything)} wiki pages** · {unreviewed} unreviewed", "",
        "## Sections",
    ]
    for d in DOMAINS:
        n = len(pages.get(d, []))
        root.append(f"- [[{TITLES[d]}]] ({n}) — {BLURB[d]}")
    root += ["", "## Recently updated"]
    root += [line(pg) for pg in recent] or ["_Nothing yet._"]
    root += ["", "## Special pages",
             "- [[hot]] — current focus, active projects, open loops (rewritten at /close and /weekly)",
             "- [[log]] — append-only history of every ingest, save, lint and review",
             "- [[Home]] — dashboards · [[Memex Manual]] — how to use Memex", ""]
    if write(ROOT / "wiki" / "index.md", "\n".join(root)):
        changed.append("index")
    print(f"index: {len(everything)} pages; updated: {', '.join(changed) if changed else 'no changes'}")


if __name__ == "__main__":
    main()
