#!/usr/bin/env python3
"""Regenerate Memex's catalog from page frontmatter.

Writes wiki/index.md (root) and one "<Title>.md" section index per active domain (titles, blurbs and
folder order come from the domain config: schema/domains.json plus the vault's .memex/). Generated
indexes of domains the vault no longer uses are removed. Each line: - [[Page]] — summary · status · updated.
Never hand-edit the outputs; fix `summary:` instead.
Usage: memex index  (or python3 tools/build_index.py)
"""
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from memexlib import domain_specs, frontmatter, iter_files, rel, require_vault, special  # noqa: E402

ROOT = require_vault()
SPECS = domain_specs(ROOT)
DOMAINS = [d["name"] for d in SPECS]
SECTION_ORDER = {d["name"]: d["folders"] for d in SPECS}
TITLES = {d["name"]: d["title"] for d in SPECS}
BLURB = {d["name"]: d["blurb"] for d in SPECS}
SPECIAL = special(ROOT)


def load_pages():
    pages = defaultdict(list)
    for p in iter_files(ROOT / "wiki", exts=(".md",)):
        r = rel(p)
        if r in SPECIAL:
            continue
        parts = r.split("/")
        if len(parts) < 3 or parts[1] not in DOMAINS:
            continue
        fm, _ = frontmatter(p.read_text(encoding="utf-8", errors="ignore"))
        folder = parts[2] if len(parts) > 3 else "(root)"
        pages[parts[1]].append({
            "name": p.stem, "folder": folder, "summary": str(fm.get("summary") or "").strip(),
            "status": str(fm.get("status") or "").strip(), "updated": str(fm.get("updated") or "").strip(),
            "reviewed": str(fm.get("reviewed") or "").strip(), "type": str(fm.get("type") or "").strip(),
        })
    return pages


def line(pg):
    bits = [f"- [[{pg['name']}]]"]
    bits.append(f" — {pg['summary']}" if pg["summary"] else " — ⚠ no summary")
    meta = []
    if pg["status"] and pg["status"] not in ("active",):
        meta.append(pg["status"])
    if pg["updated"]:
        meta.append(pg["updated"])
    if not pg["reviewed"]:
        meta.append("unreviewed")
    if meta:
        bits.append(f" · _{' · '.join(meta)}_")
    return "".join(bits)


def write(path: Path, content: str):
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8")
        return True
    return False


def drop_stale_indexes(changed):
    """Remove generated section indexes left behind by domains the vault no longer uses."""
    wiki = ROOT / "wiki"
    if not wiki.exists():
        return
    for d in sorted(p for p in wiki.iterdir() if p.is_dir() and p.name not in DOMAINS):
        for f in d.glob("* Index.md"):
            fm, _ = frontmatter(f.read_text(encoding="utf-8", errors="ignore"))
            if str(fm.get("generated", "")).lower() == "true" and fm.get("type") == "index":
                f.unlink()
                changed.append(f"removed {rel(f)}")


def main():
    pages = load_pages()
    changed = []
    drop_stale_indexes(changed)
    for d in DOMAINS:
        items = pages.get(d, [])
        by_folder = defaultdict(list)
        for pg in items:
            by_folder[pg["folder"]].append(pg)
        order = SECTION_ORDER[d] + sorted(f for f in by_folder if f not in SECTION_ORDER[d])
        out = [
            "---", "type: index", f"domain: {d}", "generated: true", "---",
            f"> [!info] Generated by `memex index` — do not edit. {len(items)} pages.",
            "", BLURB[d], "",
        ]
        for f in order:
            if f not in by_folder:
                continue
            out.append(f"## {f.capitalize()} ({len(by_folder[f])})")
            out += [line(pg) for pg in sorted(by_folder[f], key=lambda x: x["name"].lower())]
            out.append("")
        if not items:
            out.append("_No pages yet._\n")
        if write(ROOT / "wiki" / d / f"{TITLES[d]}.md", "\n".join(out).rstrip() + "\n"):
            changed.append(TITLES[d])

    everything = [pg for d in DOMAINS for pg in pages.get(d, [])]
    recent = sorted((pg for pg in everything if pg["updated"]), key=lambda x: (x["updated"], x["name"].lower()), reverse=True)[:12]
    unreviewed = sum(1 for pg in everything if not pg["reviewed"])
    root = [
        "---", "type: index", "generated: true", "---",
        "> [!info] Generated by `memex index` — do not edit. Start every lookup here, then open a section index.",
        "", "# Memex Index", "",
        f"**{len(everything)} wiki pages** · {unreviewed} unreviewed", "",
        "## Sections",
    ]
    for d in DOMAINS:
        n = len(pages.get(d, []))
        root.append(f"- [[{TITLES[d]}]] ({n}) — {BLURB[d]}")
    root += ["", "## Recently updated"]
    root += [line(pg) for pg in recent] or ["_Nothing yet._"]
    root += ["", "## Special pages",
             "- [[hot]] — current focus, active projects, open loops (rewritten at /close and /weekly)",
             "- [[log]] — append-only history of every ingest, save, lint and review",
             "- [[Home]] — dashboards · [[Memex Manual]] — how to use Memex", ""]
    if write(ROOT / "wiki" / "index.md", "\n".join(root)):
        changed.append("index")
    print(f"index: {len(everything)} pages; updated: {', '.join(changed) if changed else 'no changes'}")


if __name__ == "__main__":
    main()
